/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  common\MotionProfiles.h
 *  model: RELbotSimple
 *  expmt: RELbotSimple
 *  date:  April 9, 2026
 *  time:  1:30:42 PM
 *  user:  Universiteit Twente
 *  from:  -
 *  build: 5.1.6.14106
 **********************************************************/

/* This file defines the functions necessary for motion profiles
   functions
*/
