/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  common\MotionProfiles.h
 *  model: RELbotSimple
 *  expmt: RELbotSimple
 *  date:  April 2, 2026
 *  time:  9:03:39 PM
 *  user:  20-sim 5.1 Professional
 *  from:  Demo/Viewer License
 *  build: 5.1.6.14106
 **********************************************************/

/* This file defines the functions necessary for motion profiles
   functions
*/
