/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  common\MotionProfiles.cpp
 *  subm:  LoopController
 *  model: RELbotSimple
 *  expmt: RELbotSimple
 *  date:  April 16, 2026
 *  time:  6:50:08 PM
 *  user:  Universiteit Twente
 *  from:  -
 *  build: 5.1.6.14106
 **********************************************************/

/* This file implements the functions necessary for motion profiles
   functions
*/


